apiVersion: v1
kind: Secret
metadata:
  name: envsync-secrets
  namespace: envsync
type: Opaque
data:
  JWT_SECRET: ZW52c3luYw==
  SECRET_MASTER_KEY: MzJfY2hhcl9zdXBlcl9zZWNyZXRfbWFzdGVyX2tleSEh
  BREVO_API_KEY: eGtleXNpYi02MmMyOTQ3MzVkZGFkNGM3ZTY2OGRiOGYzNjU0M2Y0N2RhNDdiNjhhNzdiOTdhZWJkYTNiNGM2MmQzOTA3MTQxLVJwUTlqMklPREFrQmVyZ1U=
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9lbnZzeW5j
